name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  UDEPS_VERSION: 0.1.50
  NODE_VERSION: 20

jobs:
  All:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref == 'refs/heads/main' }}
    - name: Lint
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Fmt
      run: cargo fmt --all -- --check
    - name: Check docs
      run: cargo doc --no-deps --document-private-items
      env:
        RUSTDOCFLAGS: "-D warnings"
    - name: Run tests
      run: cargo test --verbose

  Dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - name: Install udeps
      uses: taiki-e/install-action@cargo-udeps
    - name: Check for unused dependencies
      run: cargo udeps --all-targets

  React:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref == 'refs/heads/main' }}
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: explorer/package-lock.json
    - name: Install wasm-pack
      uses: taiki-e/install-action@wasm-pack
    - name: Install dependencies
      run: cd explorer && npm ci
    - name: Test compilation
      run: cd explorer && CI=true npm run build

  WASM:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref == 'refs/heads/main' }}
    - name: Build types
      run: cargo build --target wasm32-unknown-unknown --release --manifest-path types/Cargo.toml && du -h target/wasm32-unknown-unknown/release/alto_types.wasm
    - name: Install wasm-pack
      uses: taiki-e/install-action@wasm-pack
    - name: Pack types
      run: wasm-pack build types --release --target web
